baseURL      = "https://resume.liaosirui.com/"
languageCode = "en-us"
title        = "廖思睿的简历"

disable404     = true
disableRSS     = true
disableSitemap = true

[params]
    author      = "Sirui Liao"
    description = "Sirui Liao's Resume"
    styles      = "styles-6.css"

    [params.profile]
        avatar  = "srliao.png"
        en_name = "Sirui Liao"
        name    = "廖思睿"
        tagline = "运维研发"

    [params.contact]
        enable = true

        [[params.contact.list]]
            class = "email"
            icon  = "fa-sex"
            title = "性别/年龄: 男 27"
            url   = ""

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "5 年工作经验"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-envelope"
            title = "Email: cyril@liaosirui.com"
            url   = "mailto: cyril@liaosirui.com"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-phone"
            title = "联系电话: 13018213369"
            url   = "tel:+86 13018213369"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "个人博客: blog.liaosirui.com"
            url   = "https://blog.liaosirui.com"

    [params.education]
        enable = true
        title  = "Education"

        [[params.education.list]]
            college = "成都理工大学"
            dates   = "2016.09 - 2020.06"
            degree  = "物联网工程 本科"
            gpa     = "GPA: 3.6/5.0(专业前 10%)"

        [[params.education.list]]
            college = "四川省绵阳南山中学"
            dates   = "2013.09 - 2016.06"
            degree  = "高中"

    [params.summary]
        enable = true
        icon = "fa-user"
        summary = """毕业于成都理工大学, 物联网工程专业, 成都理工大学优秀毕业生、成都理工大学荣誉学士学位 (优等生学位)

主要技能: 

○ 基于 Kubernetes 和容器化技术进行投研开发环境管理, 深度整合阿里云等云商构建混合云算力调度

○ 建设高性能基础设施, 支撑因子、数据系统, 包括: 并行文件系统、IB 网络、K8s / Airflow 调度框架

○ 深度参与过交易机房网络构建、托管机器管理、高频机调优、低延迟网卡实施等
"""
        title = "Career Profile"

    [params.experiences]
        enable = true
        icon   = "fa-briefcase"
        title  = "Experiences"

    [[params.jobs.list]]
        company  = "上海量魁资产管理有限公司"
        dates    = "2024.03 - 至今"
        details  = "负责公司因子平台、实时行情、数据平台、交易平台等业务的基础设施, 建设基于 K8s 的投研开发环境、并行存储、交易专线网络等"
        position = "运维-基础设施组负责人"
    [[params.jobs.list]]
        company  = "成都宽邦科技有限公司"
        dates    = "2020.12 - 2023.12"
        details  = "参与 BigQuant AI 量化平台 (https://bigquant.com)后端开发及运维工作、参与公司内部 DevOps 流程建设"
        position = "后端开发工程师 / 运维研发工程师"
    [[params.jobs.list]]
        company  = "北京凝思软件股份有限责任公司四川分公司"
        dates    = "2020.06 - 2020.11"
        details  = "在公司的凝思安全容器系统项目中，负责底层网络实现"
        position = "容器研发工程师"

    [params.projects]
        enable = true
        icon   = "fa-archive"
        intro  = "上海量魁私募基金基础设施建设主要工作成果："
        title  = "Projects"
        [[params.projects.list]]
            tagline = """
- 使用 K8s 抽象底层机器资源，对 K8s 进行扩展开发，对用户开发环境使用容器进行统一管理，降低用户提交任务的复杂度。
- 引入并行文件系统、列式存储格式，加速用户读取逐笔、快照数据（原方案为 ClickHouse）。
- 统一调度 CPU / GPU 资源。
- 交易策略任务由 K8s 进行调度，结合监控系统增强可观测性。
- 结合阿里云等云商的按需付费实例扩充本地算力，用较低成本解决算力需求峰值。
"""
            title   = "基于 K8s 的投研开发环境"
        [[params.projects.list]]
            tagline = """
- 统一使用瘦终端访问内外网分离的云桌面办公，保护公司代码、数据等核心数据资产
- 其他公司内办公软件的整合
"""
            title   = "云桌面办公环境"
        [[params.projects.list]]
            tagline = """
- 构建网络、消息队列设施，支撑构建实时行情回传（仿真需求）
- 负责 Airflow 调度系统的运维、监控等，支撑数据、因子的任务
"""
            title   = "公司内部基础设施支持"
        [[params.projects.list]]
            tagline = """
- 构建本地机房、专线、交易所托管机房的一体化网络结构
- 基于 14900KS、9950X 等交易高频机的调优
- 参与公司交易低延迟网络（Solarflare、Cisco 等）网络解决方案铺设
"""
            title   = "交易机器、网络管理"

    [params.skills]
        enable = false
        icon   = "fa-rocket"
        title  = "Skills & Proficiency"

        [[params.skills.list]]
            level = "98%"
            skill = "Python & Django"

    [params.footer]
        copyright = '[川公网安备51010702043024号](http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=51010702043024) | [蜀ICP备17003301号-1](http://beian.miit.gov.cn/)'
