baseURL      = "https://resume.liaosirui.com/"
languageCode = "en-us"
title        = "廖思睿的简历"

disable404     = true
disableRSS     = true
disableSitemap = true

[params]
    author      = "Sirui Liao"
    description = "Sirui Liao's Resume"
    styles      = "styles-6.css"

    [params.profile]
        avatar  = "srliao.png"
        en_name = "Sirui Liao"
        name    = "廖思睿"
        tagline = "后台开发工程师"

    [params.contact]
        enable = true

        [[params.contact.list]]
            class = "email"
            icon  = "fa-sex"
            title = "性别/年龄: 男 25"
            url   = ""

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "3 年工作经验"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-envelope"
            title = "Email: cyril@liaosirui.com"
            url   = "mailto: cyril@liaosirui.com"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-phone"
            title = "联系电话: 13018213369"
            url   = "tel:+86 13018213369"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "个人博客: blog.liaosirui.com"
            url   = "https://github.com/LiaoSirui/blog.liaosirui.com"

[params.education]
    enable = true
    title  = "Education"

    [[params.education.list]]
        college = "成都理工大学"
        dates   = "2016.09 - 2020.06"
        degree  = "物联网工程 本科"
        gpa     = "GPA: 3.6/5.0(专业前 10%)"

    [[params.education.list]]
        college = "四川省绵阳南山中学"
        dates   = "2013.09 - 2016.06"
        degree  = "高中"

[params.language]
    enable = true
    title  = "Languages"

    [[params.language.list]]
        language = "英语四级"
        level    = "564分"

    [[params.language.list]]
        language = "英语六级"
        level    = "423分"

[params.interests]
    enable = true
    title  = "Interests"

    [[params.interests.list]]
        interest = "(1) 容器相关: Docker / K8s / Docker Compose"

    [[params.interests.list]]
        interest = "(2) Linux 基础, 了解 Centos / Alpine / RockyLinux 等"

    [[params.interests.list]]
        interest = "(3) Python 编程和 Golang 编程经验"

    [[params.interests.list]]
        interest = "(4) 运维与监控: Ansible / Sealos / Prometheus + Grafana"

[params.summary]
    enable = true
    icon = "fa-user"
    summary = """毕业于成都理工大学, 物联网工程专业, 获得成都理工大学荣誉学士学位 (优等生学位), 获得成都理工大学优秀毕业生, 主修课程: 程序设计基础(C++)、JAVA 程序开发、嵌入式 Linux 开发、数据库原理、FPGA 设计及其他计算机基础课程

证书:

○ 软件设计师(中级, 2023 年上半年)

主要技能: 

○ Kubernetes 技术栈: 熟练使用 Kubernetes 进行容器编排和管理, 包括部署、调度、监控和维护

○ Kubernetes Operator 开发: 在 Kubernetes 上设计、开发和维护自定义的 Operators, 以简化和自动化应用程序的运维工作

○ 容器化技术: 熟悉 Docker / Containerd / Podman 和容器化应用程序, 能够构建、优化和管理容器化工作负载

○ 持续集成/持续部署 (CI/CD): 使用 K8s 和相关工具实施 CI/CD 流程, 提高软件交付效率
"""
    title = "Career Profile"

[params.experiences]
    enable = true
    icon   = "fa-briefcase"
    title  = "Experiences"

[[params.jobs.list]]
    company  = "成都宽邦科技有限公司"
    dates    = "2020.12 - 2023.12"
    details  = "在职期间参与公司产品研发与项目, 包括 BigQuant AI 量化平台 (产品) 及 B 端项目的维护；负责后端开发工作和维护, **主要技术栈: Kuberntes、Prometheus Stack、ES Log Stack、OpenTelementery / Jaeger、BeeGFS(并行文件系统)、Golang / Gin (Golang 开发)、Python / Fastapi / Django (Python 开发) 等**"
    position = "后端开发工程 / 运维研发工程师"
[[params.jobs.list]]
    company  = "北京凝思软件股份有限责任公司四川分公司"
    dates    = "2020.06 - 2020.11"
    details  = "在职期间参与公司新开发的凝思安全容器系统项目, 负责底层网络实现, 使用 **OpenVSwitch** 和 **Golang** 构建容器运行的网络环境"
    position = "软件开发工程师"

[params.projects]
    enable = true
    icon   = "fa-archive"
    title  = "Projects"

    [[params.projects.list]]
        tagline = """BigQuant 人工智能量化投资交易平台(https://bigquant.com), 包括量化策略平台的开发运营和 PAAS 平台的运营维护, 产品主要为用户提供量化投研环境

主要工作: 

(1) CI/CD 环境搭建与制品管理

○ 在 GitLab 和 GitLab Runner 基础上构建 CI 环境，利用 Ansible 构建 CD 环境

○ 使用 Nexus 和 Artifactory 管理内部镜像源，熟悉 Harbor 的搭建与维护，利用 Harbor 进行镜像管理

(2) Kubernetes 基础和开发 Kubernetes 管理面板

○ 熟悉 Kubernetes 基础以及 Docker / Containerd, 有过 Docker 升级至 Containerd 经验, 熟悉容器技术原理

○ 有使用 Calico、Cilium CNI 的经验, 熟悉 LVS、MetalLB、KeepAlived 负载均衡技术

○ 基于 OKD Console (OpenShift 的开源版本) 构建 Kubernetes 管理面板，进行深度定制，包括镜像管理和结合 Dex IdP 进行 OAuth 认证等的定制化开发和维护

(3) 线上环境监控与告警

○ 利用 Prometheus、Grafana 和 Alertmanager 构建线上环境的监控与告警系统，确保系统稳定性和及时发现问题

(4) 日志系统搭建与维护

○ 使用 Vector 和 ElasticSearch 构建日志系统，熟悉 ES master/data/client 节点的搭建与维护，使用 Vector 进行节点日志采集和 remap 处理

(5) 可视化链路追踪系统

○ 基于 OpenTelemetry 和 Jaeger 构建可视化链路追踪系统，熟悉 Jaeger 的搭建与维护，使用 OpenTelemetry 进行链路追踪数据采集

(6) Service Mesh 环境搭建

○ 构建基于 Istio 的 Service Mesh 环境，熟悉 Istio 的搭建与维护，应用于流量管理、流量镜像、流量限制、流量熔断、流量重试和流量注入等场景

(7) Operator 开发与环境管理

○ 熟悉开发 Operator, 独立完成用户权限控制和镜像上传功能

○ 结合 MutatingWebhook 完成开发环境 (即用户 Pod) 的管理，引入 lxcfs 解决 cgroups 无法显示 Pod 真实负载问题

(8) 并行文件系统搭建与维护

○ 引入 BeeGFS 并行文件系统，提升数据读取速度，熟悉 BeeGFS 的搭建与维护，并深入分析 BeeGFS 的工作原理

(9) 多语言开发经验

○ 具有 Golang 和 Python 的开发经验

○ 熟悉 Gin Web 后端的开发

○ 引入 FastAPI 作为后端框架，参与公司基础库的编写

(10) 日常运维工作：

○ 参与日常运维工作，具备使用 Ansible 自动化运维工具、IPTables/IPvs 调试、JumpServer 等经验

○ 优化网关，采用 OpenResty + Lua + Redis 替换原 JupyterHub 部分

○ 具有使用 Nginx Ingress 的经验(包括 nginxc、kubernetes 社区版本)

○ 熟悉 Nginx / Openresty 的配置和使用, 有编译模块的经验
"""
        title = "BigQuant AI 量化平台"
        url = "https://bigquant.com/"

    [[params.projects.list]]
        tagline = """凝思安全容器系统软件(https://www.linx-info.com)是基于凝思安全操作系统完全自主研发, 具备容器隔离特性的容器产品, 同时采用了一系列的安全技术避免了现有容器技术的安全风险

主要工作:

○ 负责底层网络实现, 使用 OpenVSwitch 和 Golang 构建容器运行的网络环境, 提供网络流量控制等功能
"""
        title   = "凝思安全容器系统"
        url     = "https://www.linx-info.com"

[params.skills]
    enable = false
    icon   = "fa-rocket"
    title  = "Skills & Proficiency"

    [[params.skills.list]]
        level = "98%"
        skill = "Python & Django"

[params.footer]
    copyright = "备案号: 蜀ICP备17003301号-1"
